openapi: 3.0.1
info:
  title: Boarding API
  description: |
    # Introduction
    TODO.
  contact:
    name: Support Team
    url: https://worldnettps.com/contact/
    email: support@worldnettps.com
  version: v2
  x-logo:
    url: worldnet-logo.png
    backgroundColor: '#FFFFFF'
    altText: Worldnet
servers:
- url: https://devpayments.worldnettps.com/merchant
  description: Sandbox Server
tags:
- name: tokens
  description: TODO
  x-displayName: Access Tokens
- name: partners
  description: TODO
  x-displayName: Partners
- name: merchantPortfolios
  description: TODO
  x-displayName: Merchant Portfolios
- name: merchants
  description: TODO
  x-displayName: Merchants
- name: users
  description: TODO
  x-displayName: Users
- name: terminals
  description: TODO
  x-displayName: Terminals
- name: templates
  description: TODO
  x-displayName: Templates
paths:
  /api/v2/boarding/authenticate:
    get:
      tags:
      - tokens
      summary: Authenticate
      description: Use this operation to exchange your `API Key` for a `JWT Token` that will give you access to the API.
      operationId: authenticate
  /api/v2/boarding/merchants/{merchantId}/users/{userId}/activate:
    patch:
      tags:
      - users
      summary: Activate User
      operationId: activateUser
      security:
      - Bearer:
        - users:full-access
  /api/v2/boarding/merchants/{merchantId}/users/{userId}/deactivate:
    patch:
      tags:
      - users
      summary: Deactivate User
      operationId: deactivateUser
      security:
      - Bearer:
        - users:full-access
  /api/v2/boarding/merchants/{merchantId}/users/{userId}/lock:
    patch:
      tags:
      - users
      summary: Lock User
      operationId: lockUser
      security:
      - Bearer:
        - users:full-access
  /api/v2/boarding/merchants/{merchantId}/users/{userId}/unlock:
    patch:
      tags:
      - users
      summary: Unlock User
      operationId: unlockUser
      security:
      - Bearer:
        - users:full-access
  /api/v2/boarding/merchants/{merchantId}/users/{userId}:
    get:
      tags:
      - users
      summary: Get User
      operationId: getUser
      security:
      - Bearer:
        - users:full-access
        - users:read-only
    put:
      tags:
      - users
      summary: Update User
      operationId: updateUser
      security:
      - Bearer:
        - users:full-access
  /api/v2/boarding/merchants/{merchantId}/users:
    get:
      tags:
      - users
      summary: List Users
      operationId: listUsers
      security:
      - Bearer:
        - users:full-access
        - users:read-only
    post:
      tags:
      - users
      summary: Create User
      operationId: createUser
      security:
      - Bearer:
        - users:full-access
  /api/v2/boarding/merchants/{merchantId}/terminals/{terminalNumber}/deactivate:
    patch:
      tags:
      - terminals
      summary: Deactivate Terminal
      operationId: deactivateTerminal
      security:
      - Bearer:
        - terminals:full-access
  /api/v2/boarding/merchants/{merchantId}/terminals/{terminalNumber}:
    get:
      tags:
      - terminals
      summary: Get Terminal
      operationId: getTerminal
      security:
      - Bearer:
        - terminals:full-access
        - terminals:read-only
    put:
      tags:
      - terminals
      summary: Update Terminal
      operationId: updateTerminal
      security:
      - Bearer:
        - terminals:full-access
  /api/v2/boarding/merchants/{merchantId}/terminals:
    get:
      tags:
      - terminals
      summary: List Terminals
      operationId: listTerminals
      security:
      - Bearer:
        - terminals:full-access
        - terminals:read-only
    post:
      tags:
      - terminals
      summary: Create Terminal
      operationId: createTerminal
      security:
      - Bearer:
        - terminals:full-access
  /api/v2/boarding/merchants/{merchantId}/terminals/{terminalNumber}/activate:
    patch:
      tags:
      - terminals
      summary: Activate Terminal
      operationId: activateTerminal
      security:
      - Bearer:
        - terminals:full-access
  /api/v2/boarding/merchants:
    get:
      tags:
      - merchants
      summary: List Merchants
      operationId: listMerchants
      security:
      - Bearer:
        - merchants:full-access
        - merchants:read-only
    post:
      tags:
      - merchants
      summary: Create Merchant
      operationId: createMerchant
      security:
      - Bearer:
        - merchants:full-access
  /api/v2/boarding/merchants/{merchantId}:
    get:
      tags:
      - merchants
      summary: Get Merchant
      operationId: getMerchant
      security:
      - Bearer:
        - merchants:full-access
        - merchants:read-only
    put:
      tags:
      - merchants
      summary: Update Merchant
      operationId: updateMerchant
      security:
      - Bearer:
        - merchants:full-access
  /api/v2/boarding/merchants/{merchantId}/activate:
    patch:
      tags:
      - merchants
      summary: Activate Merchant
      operationId: activateMerchant
      security:
      - Bearer:
        - merchants:full-access
  /api/v2/boarding/merchants/{merchantId}/deactivate:
    patch:
      tags:
      - merchants
      summary: Deactivate Merchant
      operationId: deactivateMerchant
      security:
      - Bearer:
        - merchants:full-access
  /api/v2/boarding/merchantPortfolios/{merchantPortfolioId}:
    get:
      tags:
      - merchantPortfolios
      summary: Get Merchant Portfolio
      operationId: getMerchantPortfolio
      security:
      - Bearer:
        - merchant-portfolios:full-access
        - merchant-portfolios:read-only
    put:
      tags:
      - merchantPortfolios
      summary: Update Merchant Portfolio
      operationId: updateMerchantPortfolio
      security:
      - Bearer:
        - merchant-portfolios:full-access
  /api/v2/boarding/merchantPortfolios/{merchantPortfolioId}/activate:
    patch:
      tags:
      - merchantPortfolios
      summary: Activate Merchant Portfolio
      operationId: activateMerchantPortfolio
      security:
      - Bearer:
        - merchant-portfolios:full-access
  /api/v2/boarding/merchantPortfolios/{merchantPortfolioId}/deactivate:
    patch:
      tags:
      - merchantPortfolios
      summary: Deactivate Merchant Portfolio
      operationId: deactivateMerchantPortfolio
      security:
      - Bearer:
        - merchant-portfolios:full-access
  /api/v2/boarding/merchantPortfolios:
    get:
      tags:
      - merchantPortfolios
      summary: List Merchant Portfolios
      operationId: listMerchantPortfolios
      security:
      - Bearer:
        - merchant-portfolios:full-access
        - merchant-portfolios:read-only
    post:
      tags:
      - merchantPortfolios
      summary: Create Merchant Portfolio
      operationId: createMerchantPortfolio
      security:
      - Bearer:
        - merchant-portfolios:full-access
  /api/v2/boarding/partners/{partnerPortfolioId}:
    get:
      tags:
      - partners
      summary: Get Partner
      operationId: getPartner
      security:
      - Bearer:
        - partners:full-access
        - partners:read-only
    put:
      tags:
      - partners
      summary: Update Partner
      operationId: updatePartner
      security:
      - Bearer:
        - partners:full-access
  /api/v2/boarding/partners/{partnerPortfolioId}/activate:
    patch:
      tags:
      - partners
      summary: Activate Partner
      operationId: activatePartner
      security:
      - Bearer:
        - partners:full-access
  /api/v2/boarding/partners/{partnerPortfolioId}/deactivate:
    patch:
      tags:
      - partners
      summary: Deactivate Partner
      operationId: deactivatePartner
      security:
      - Bearer:
        - partners:full-access
  /api/v2/boarding/partners:
    get:
      tags:
      - partners
      summary: List Partners
      operationId: listPartners
      security:
      - Bearer:
        - partners:full-access
        - partners:read-only
    post:
      tags:
      - partners
      summary: Create Partner
      operationId: createPartner
      security:
      - Bearer:
        - partners:full-access
  /api/v2/boarding/templates/terminals/{templateName}:
    get:
      tags:
      - templates
      summary: Get Terminal Template
      operationId: getTerminalTemplate
      security:
      - Bearer:
        - templates:full-access
        - templates:read-only
  /api/v2/boarding/templates/users/{templateName}:
    get:
      tags:
      - templates
      summary: Get User Template
      operationId: getUserTemplate
      security:
      - Bearer:
        - templates:full-access
        - templates:read-only
  /api/v2/boarding/templates/merchants/{templateName}:
    get:
      tags:
      - templates
      summary: Get Merchant Template
      operationId: getMerchantTemplate
      security:
      - Bearer:
        - templates:full-access
        - templates:read-only
components:
  securitySchemes:
    Basic:
      type: http
      description: |
        Use `Basic` authentication scheme to exchange your API Key for JWT Access Tokens.
      scheme: basic
    Bearer:
      type: http
      description: |
        Use `Bearer` authentication scheme to prove your identity and access protected resources.
      scheme: bearer
      bearerFormat: JWT
